[package]
name = "rust-concurrency"
version = "0.1.0"
authors = ["Nils Jørgen Mittet <njmittet@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
